# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geemap
                                 A QGIS plugin
 Cloud-based geospatial analysis with Google Earth Engine and geemap
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-14
        copyright            : (C) 2023 by Qiusheng Wu
        email                : giswqs@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geemap class from file Geemap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geemap import Geemap
    return Geemap(iface)
